apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: feast-benchmark

resources:
  - ../../base
  - ../../stores

# State Farm exact SLA requirements:
# - 60ms p99 latency
# - 3M transactions/hour
# - 50 and 200 entities
# - 200 features
configMapGenerator:
  - name: benchmark-config
    behavior: merge
    literals:
      - FEATURES=200
      - ENTITIES=50,200
      - FV_COUNTS=1
      - FEATURE_SERVICES=1
      - TRANSFORMATIONS=none
      - COMPRESSION=none
      - ITERATIONS=50
      - WARMUP=10
      - SLA_P99_MS=60
      - SLA_THROUGHPUT_RPH=3000000
      - REDIS_HOST=redis.feast-benchmark.svc.cluster.local
      - REDIS_PORT=6379
      - POSTGRES_HOST=postgres.feast-benchmark.svc.cluster.local
      - POSTGRES_PORT=5432
      - POSTGRES_DATABASE=feast
